### ISSUE TITLE
Warning-rejecting builds for the CI system

### ISSUE THREAD

**Issue by stephenswat** [acts-project/traccc#64] opened 2021-08-05 13:58 UTC
This is a continuation of the discussion in #63 (@paulgessinger, @krasznaa). We want to add a CI build which has `-Werror` enabled so we can reject code that generates compiler warnings. I see three options for doing this:

1. Add the `-Werror` flag to `Debug` builds on a CMake level.
2. Add the `-Werror` flag to the CI system via the environment variables.
3. Add a new `CI` build type to CMake, which has `-Werror`.

Thoughts?

**Comment by paulgessinger** [comment] 2021-08-05 14:02
I'd just change [this line](https://github.com/acts-project/traccc/blob/main/.github/workflows/builds.yml#L29) to 
```cmake
 run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DCMAKE_CXX_FLAGS="-Werror" -B build -S .
```

**Comment by krasznaa** [comment] 2021-08-05 14:08
Yeah, that should be a fine setup. We'll just need to make sure that developers will know how to reproduce the behaviour in their own builds. Since I can see some people getting confused by this setup. (Getting a failure in the CI while their own build succeeded.) But I might just be paranoid...

So yes, this should be fine. (I myself was mentioning the `CXXFLAGS` environment variable just because in ATLAS offline builds we use that in such cases. As that is convenient to use with our "build scripts".)

**Comment by beomki-yeo** [comment] 2022-04-05 18:15
Is this still an issue?

**Comment by krasznaa** [comment] 2022-04-06 06:42
Ever since #132 most warnings became errors in our builds with `CMAKE_BUILD_TYPE=Debug`.

But it may be worth keeping this issue open for a bit longer. We still have a couple of warnings in the CUDA builds. Notably:

```
/__w/traccc/traccc/build/_deps/detray-src/core/include/detray/grids/grid2.hpp(183): warning #20011-D: calling a __host__ function("std::vector< ::traccc::internal_spacepoint< ::traccc::spacepoint> ,    ::std::pmr::polymorphic_allocator< ::traccc::internal_spacepoint< ::traccc::spacepoint> > > ::vector(const ::std::vector< ::traccc::internal_spacepoint< ::traccc::spacepoint> ,    ::std::pmr::polymorphic_allocator< ::traccc::internal_spacepoint< ::traccc::spacepoint> > > &)") from a __host__ __device__ function("detray::grid2< ::detray::attach_populator,  ::detray::axis::circular,  ::detray::axis::regular,  ::detray::serializer2,  ::detray::dvector,  ::detray::djagged_vector,  ::detray::darray,  ::detray::dtuple,  ::traccc::internal_spacepoint< ::traccc::spacepoint> , (bool)0, (unsigned int)1u> ::bin") is not allowed

/__w/traccc/traccc/build/_deps/detray-src/core/include/detray/grids/grid2.hpp(183): warning #20011-D: calling a __host__ function("std::vector<::std::vector< ::traccc::internal_spacepoint< ::traccc::spacepoint> ,    ::std::pmr::polymorphic_allocator< ::traccc::internal_spacepoint< ::traccc::spacepoint> > > ,    ::std::pmr::polymorphic_allocator<::std::vector< ::traccc::internal_spacepoint< ::traccc::spacepoint> ,    ::std::pmr::polymorphic_allocator< ::traccc::internal_spacepoint< ::traccc::spacepoint> > > > > ::at(unsigned long)") from a __host__ __device__ function("detray::grid2< ::detray::attach_populator,  ::detray::axis::circular,  ::detray::axis::regular,  ::detray::serializer2,  ::detray::dvector,  ::detray::djagged_vector,  ::detray::darray,  ::detray::dtuple,  ::traccc::internal_spacepoint< ::traccc::spacepoint> , (bool)0, (unsigned int)1u> ::bin") is not allowed
```

and:

```
/__w/traccc/traccc/core/include/traccc/edm/container.hpp([209](https://github.com/acts-project/traccc/runs/5840037605?check_suite_focus=true#step:6:209)): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed
          detected during instantiation of "const item_t traccc::container<header_t, item_t, vector_t, jagged_vector_t, pair_t>::at(const traccc::container<header_t, item_t, vector_t, jagged_vector_t, pair_t>::link_type &) const [with header_t=traccc::geometry_id, item_t=traccc::spacepoint, vector_t=vecmem::vector, jagged_vector_t=vecmem::jagged_vector, pair_t=std::pair]" 
/__w/traccc/traccc/core/include/traccc/edm/seed.hpp(53): here

/__w/traccc/traccc/core/include/traccc/edm/container.hpp(209): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed
          detected during instantiation of "const item_t traccc::container<header_t, item_t, vector_t, jagged_vector_t, pair_t>::at(const traccc::container<header_t, item_t, vector_t, jagged_vector_t, pair_t>::link_type &) const [with header_t=traccc::geometry_id, item_t=traccc::spacepoint, vector_t=vecmem::vector, jagged_vector_t=vecmem::jagged_vector, pair_t=std::pair]" 
/__w/traccc/traccc/core/include/traccc/edm/seed.hpp(53): here
```

I just still didn't figure out exactly how we want to deal with them... :thinking:

**Comment by paulgessinger** [comment] 2022-04-29 13:15
Coming back to this, after #165 was merged: I think it's not a great idea to have local CMake force `-Werror`, as that impacts productively a lot. 

Can we reconsider this and only to it in the CI?

**Closed** 2023-03-09 22:54 UTC
Labels: cicd, discussion
